### ISSUE TITLE
custom trained weights showing wrong labels

### ISSUE THREAD

**Issue by Mercury-ML** [BlueMirrors/Yolov5-ONNX#2]
After converting my weights.pt to weights.onnx and running inference, the detection works fine but my image labels are COCO.  How can I change the labels to my own (I'm unsure of the formatting of the json and/or yaml file).  Thanks!

**Comment by shivamswarnkar** [comment]
You can replace ```classes="coco"``` with ```classes=["your_label_1", "your_label_2", ...]``` in  [detect_video](https://github.com/BlueMirrors/Yolov5-ONNX/blob/82c30ac3a4e0621c4051f8d414f13ca41e83f773/detect.py#L12) and [detect_image](https://github.com/BlueMirrors/Yolov5-ONNX/blob/82c30ac3a4e0621c4051f8d414f13ca41e83f773/detect.py#L46)

**Comment by Mercury-ML** [comment]
Hi Shivam,
Thank you!!! That worked like a charm 😀 You really made my day!  I hope you have a great weekend.

BTW, do you happen to know of any way to make the label font smaller?  The labels are currently cluttering up the entire image.  If not, no worries.

-Stephen 

P.S.  I really like the aesthetic of the BlueMirrors website, nice!

**Comment by shivamswarnkar** [comment]
@Mercury-ML glad to know it worked. 

The font part is a little trickier since we're using CVU to draw. But you can play with the scale [here](https://github.com/BlueMirrors/cvu/blob/111e588e67afdb1f4220e4d890e5b57792575ef6/cvu/utils/draw.py#L34) to make font smaller. I'll try to add scale as a parameter whenever I have some availability. Thanks!
